language: cpp

dist: xenial

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

#install:
#  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=leak -fsanitize=undefined -fsanitize=integer -fsanitize=nullability -g"
  - cmake --build .
  - ctest -V

notifications:
  email: false